# Dataset directories
data_dir: 'data'
train_dir: 'data/fma_medium'
val_dir: 'data/valid'
ir_dir: 'data/aug/ir'
noise_dir: 'data/aug/noise'

# Model input parameters
fs: 8000
dur: 1.0
offset: 0.2
norm: 0.95
win_len: 1024
hop_len: 256
n_mels: 256
n_fft: 1024


# Dataset and Model hyperparameters
train_sz: 10000
val_sz: 500
bsz_train: 320
alpha: 4
beta: 8
layers: [1, 1, 1, 1]
tau: 0.05
lr: 5.0e-5
min_lr: 3.0e-6
n_epochs: 200
T_max: 250

# Augmentation hyperparameters
n_frames: 32 # depends on the spectrogram parameters
overlap: 0.5
tr_snr: [0, 10]
val_snr: [0, 10]
test_snr: [0, 10]
time_mask: 16
freq_mask: 128
noise_prob: 0.5
ir_prob: 0.5


# Database sizes (validation)
n_dummy: 100
n_query: 20
