# Dataset directories
data_dir: 'data'
fma_dir: '/data/EECS-Studiosync/datasets/fma_medium/'
htdemucs_dir: '/data/EECS-Studiosync/datasets/fma_medium/htdemucs'
# train_dir: 'data/fma_small_all.json'
# val_dir: 'data/fma_medium_all.json'
# ir_dir: '/data/home/acw723/datasets/ir'
# annot_path: '/data/home/acw723/datasets/sample_100/samples.csv'
annot_path: 'data/sample100_query_index.json'
# annot_path: 'data/riff_query_type.json'


# Model input parameters
arch: 'grafp'
fs: 16000
dur: 4.08
offset: 0.25
norm: 0.95
win_len: 1024
hop_len: 512
n_mels: 64
n_fft: 1024
n_peaks: 512  # max number of peaks to consider
silence: 1.0e-5

# Dataset and Model hyperparameters
bsz_train: 2048
n_filters : 8 # number of filters in the peak extraction layer
patch_frames: 8
patch_bins: 4
tau: 0.05
lr: 8.0e-5
min_lr: 7.0e-7
n_epochs: 400
T_max: 400
error_threshold: 1

# Classification hyperparameters
clf_lr: 1.0e-4
clf_bsz: 32

# Augmentation hyperparameters
n_frames: 128 # depends on the spectrogram parameters
overlap: 0.875
pitch_shift: 3
gain: 10

# Time Stretching hyperparameters
min_rate: 0.7
max_rate: 1.5

# BitCrusher hyperparameters (not utilized)
min_bit_depth: 2
max_bit_depth: 10

# Dynamic range compression hyperparameters (not utilized)
DC_threshold: [-30, 0]
DC_ratio: [2, 4, 8, 20]
DC_attack: [0.001, 0.1]
DC_release: [0.05, 1.0]


# Model architecture
d: 128
h: 1024
u: 32
dim: 2048

